DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
    `id` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(128) DEFAULT NULL,
    `last_name` VARCHAR(128) DEFAULT NULL,
    `street` VARCHAR(128) DEFAULT NULL,
    `house_number` VARCHAR(20) DEFAULT NULL,
    `postal_code` VARCHAR(20) DEFAULT NULL,
    `city` VARCHAR(64) DEFAULT NULL,
    `country` VARCHAR(128) DEFAULT NULL,
    `phone_number` VARCHAR(32) DEFAULT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `user_role` ENUM('USER','ADMIN') NOT NULL,
    `locked` TINYINT(1) DEFAULT NULL,
    `enabled` TINYINT(1) DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uc_email UNIQUE (`email`),
    CONSTRAINT pk_user PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
